# Generated by Django 3.2.5 on 2021-07-19 01:45

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210714_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[user.validators.validate_age]),
        ),
    ]
