# Generated by Django 3.2 on 2021-08-13 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower_source', to=settings.AUTH_USER_MODEL)),
                ('user_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_source', 'user_target')},
            },
        ),
    ]
