# Generated by Django 3.2 on 2021-09-13 04:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=user.models.user_avatar_directory_path),
        ),
    ]
