@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI2ODQ2ODExLCJqdGkiOiJhOWRlNmUwZTQ2YTg0NDE1YjBhNjZkZDdlY2UzYjA3YiIsInVzZXJfaWQiOjIxfQ._xbQb67aNXLLvPorLfNajxWqOx7pOh5OXEoZ6frMG_o


### User Login
POST http://127.0.0.1:8000/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "datluu.1702@gmail.com",
    "password": "12345678aa"
}


### Test Register
POST http://127.0.0.1:8000/api/v1/user/register HTTP/1.1
content-type: application/json

{
    "email": "hbc77435@eoopy.com",
    "password1": "12345678aa",
    "password2": "12345678aa",
    "age": "18",
    "first_name": "Hello"
}


### Test Register
POST http://127.0.0.1:8000/api/v1/user/register-2 HTTP/1.1
content-type: application/json

{
    "email": "rpf44610@cuoly.com",
    "password1": "12345678aa",
    "password2": "12345678aa",
    "age": "18",
    "first_name": "Hello",
    "first_name": "dj-rest-auth"
}


### User Login
POST http://127.0.0.1:8000/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "hbc77435@eoopy.com",
    "password": "12345678aa"
}


### User Login
POST http://127.0.0.1:8000/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "rpf44610@cuoly.com",
    "password": "12345678aa"
}


### User Change Password
POST http://127.0.0.1:8000/api/v1/user/change-password HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "old_password": "12345678aa",
    "new_password1": "12345678aa",
    "new_password2": "12345678aa"

}


### User Reset Password
POST http://127.0.0.1:8000/api/v1/user/reset-password HTTP/1.1
content-type: application/json

{
    "email": "hbc77435@eoopy.com"

}


### User Reset Confirm Password
POST http://127.0.0.1:8000/api/v1/user/reset-confirm-password/k/aq13c7-7d3a54347343efd56656fc170e868314/ HTTP/1.1
content-type: application/json

{
    "uid": "l",
    "token": "aq16yg-d894fbec430bbe808cb2a96e719d1ee1",
    "new_password1": "12345678ab",
    "new_password2": "12345678ab"

}


### User Profile
GET http://127.0.0.1:8000/api/v1/user/me HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### User Detail
GET http://127.0.0.1:8000/api/v1/user/20 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### User List
GET http://127.0.0.1:8000/api/v1/user/?page=2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Test URL Parameter
POST http://127.0.0.1:8000/api/v1/post/test/123 HTTP/1.1
content-type: application/json


### Post create 
POST http://127.0.0.1:8000/api/v1/post HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "Title 8",
    "content": "this is post 8",
    "mode": "PRIVATE"
}


### Post Update
PUT http://127.0.0.1:8000/api/v1/post/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "Title 8",
    "content": "this is post 8 (edited)",
    "mode": "PRIVATE"
}


### Post Detail
GET http://127.0.0.1:8000/api/v1/post/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Post List
GET http://127.0.0.1:8000/api/v1/post HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Post List
GET http://127.0.0.1:8000/api/v1/post?page=2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Post Delete
DELETE http://127.0.0.1:8000/api/v1/post/6 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Like Post 
POST http://127.0.0.1:8000/api/v1/like-post/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Unlike Post 
DELETE  http://127.0.0.1:8000/api/v1/like-post/8 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Likepost list
GET http://127.0.0.1:8000/api/v1/like-post/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Likepost list
GET http://127.0.0.1:8000/api/v1/like-post/4?page=1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment Create
POST http://127.0.0.1:8000/api/v1/comment/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "content": "This is comment for 4 again again"
}


### Comment List
GET http://127.0.0.1:8000/api/v1/comment/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment List
GET http://127.0.0.1:8000/api/v1/comment/4?page=3 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment Update
PUT http://127.0.0.1:8000/api/v1/comment/12 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "content": "This is comment for post 4"
}


### Comment Delete
DELETE  http://127.0.0.1:8000/api/v1/comment/12 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment Sublist
GET http://127.0.0.1:8000/api/v1/comment/4/sub/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment Sublist
GET http://127.0.0.1:8000/api/v1/comment/4/sub/2?page=2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Comment Create 2
POST http://127.0.0.1:8000/api/v1/comment/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "content": "This is comment for 4 again again",
    "parent_comment": 2
}