# Generated by Django 3.2.5 on 2021-07-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_likepost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
