# Generated by Django 3.2.5 on 2021-07-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='likepost',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
