# Generated by Django 3.2 on 2021-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Blocked', 'Blocked')], default='Active', max_length=10),
        ),
    ]
