# Generated by Django 3.2 on 2021-08-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagemember',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Member', 'Member')], default='Member', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmessagemember',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
