# Generated by Django 3.2 on 2021-08-14 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0006_alter_groupmessage_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmessagemember',
            unique_together={('group_message_id', 'user_id')},
        ),
    ]
