# Generated by Django 3.2 on 2021-09-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_groupmessagemember_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ('-updated_time',)},
        ),
        migrations.AlterModelOptions(
            name='groupmessagedetail',
            options={'ordering': ('-created_time',)},
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ('-updated_time',)},
        ),
        migrations.AlterModelOptions(
            name='privatemessagedetail',
            options={'ordering': ('-created_time',)},
        ),
    ]
